### PR TITLE
FinalProject_Stage2-Itr1

### PR DESCRIPTION
**Pull request by IlanBrof**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hi! Great job on the second stage of your diploma! The project will require some refactoring, but most of the issues are small and very fast to fix, I'm sure you can do it!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* The section with search results should have a grey background (on both pages).
* "Registration successful" popup doesn't correspond to figma https://prnt.sc/QTAvE16ZG6ro
* The top margin in "search results" is too big on 320

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "home" page scrolls on 491 - 580, 741 - 768
* The "saved-news" page scrolls on 491 - 580, 741 - 804

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* BEM entity can't consist only a modifier https://prnt.sc/x4hFmv93tS2P, `header__logout-button_active`
* `about__image`, `about__content` and other elements are used outside of their block (check the name of the block)

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* There should be only one h1 per page.
* Links in `header` and `footer` should be in nav, ul or ul inside nav.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.

* "Registration successful" popup doesn't close by closing button

- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.

* Please, fix css validation error: https://prnt.sc/4G8SnyMVzyGQ (PopupWithForm.css). There is also a validation error in NewsCard.css, 

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* https://prnt.sc/SHfckviWguv_ caption isn't displayed, there should be text as in figma https://prnt.sc/62fXi_JW1iE-
* "active" state of "search" button is missing
* Boorkmark icon should be grey when not hovered over: https://prnt.sc/AB2P5SWar3mK

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.

* Please correct all similar issues https://prnt.sc/EIyrs1Y6s3K3

- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 50

**Comment by IlanBrof** [comment]
Second iteration was committed

**Comment by ImaliaNsk** [comment]
Good job! Only a few more issues are left to fix.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* The sections now have a grey background, but please note that the cards should have a white background, not only on hover.
* On "saved-news", only the section with cards should be grey, the container with username and other text info (`saved-news__text-content`) should be white, please check the design.

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "home" page scrolls on 741 - 768

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* BEM entity can't consist only a modifier https://prnt.sc/9ChMcGNwrD3B, `header__logout-button_active`, `header__logo_sn`, `header__hamburger-menu-btn_sn` and 

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 70

## Additional comments:

* Please, note that limited height for `main` block should be removed, currently it can't contain its content https://prnt.sc/BVplKpy4yoIO

* Please, fix css validation error: https://prnt.sc/4G8SnyMVzyGQ (PopupWithForm.css). There is also a validation error in NewsCard.css

**Comment by IlanBrof** [comment]
Third iteration was committed

**Comment by ImaliaNsk** [comment]
Hi! The score is enough to accept the project, so you can move on to the next stage. However, the "Home" page still has a horizontal scroll, which should be fixed. Good luck!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The "home" page scrolls on 769 - 1132. Please, check the properties for news cards list, especially for the title in it.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.

* BEM entity can't consist only a modifier `header_sn`, `header__menu_sn` and other simliar cases

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 83

## Additional comments:

* Please, fix css validation error: https://prnt.sc/4G8SnyMVzyGQ (PopupWithForm.css). There is also a validation error in NewsCard.css

**Pull request merged**
